export const RING_CENTRAL_SEND_SMS_START = 'RING_CENTRAL_SEND_SMS_START';
export const RING_CENTRAL_SEND_SMS_SUCCESS = 'RING_CENTRAL_SEND_SMS_SUCCESS';
export const RING_CENTRAL_SEND_SMS_ERROR = 'RING_CENTRAL_SEND_SMS_ERROR';