export const INPUT_DATA_CONTACT_FORM = 'INPUT_DATA_CONTACT_FORM';
export const RESET_STATE_CONTACT_DETAIL = 'RESET_STATE_CONTACT_DETAIL';

export const GET_DETAIL_CONTACT_START = 'GET_DETAIL_CONTACT_START';
export const GET_DETAIL_CONTACT_SUCCESS = 'GET_DETAIL_CONTACT_SUCCESS';
export const GET_DETAIL_CONTACT_ERROR = 'GET_DETAIL_CONTACT_ERROR';

export const UPDATE_DETAIL_CONTACT_START = 'UPDATE_DETAIL_CONTACT_START';
export const UPDATE_DETAIL_CONTACT_SUCCESS = 'UPDATE_DETAIL_CONTACT_SUCCESS';
export const UPDATE_DETAIL_CONTACT_ERROR = 'UPDATE_DETAIL_CONTACT_ERROR';